# Generated by Django 5.1.7 on 2025-04-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'Ordenes'},
        ),
    ]
